x = (int(17))
y = (float(3.2))
print ("Expressão A x / 4 + y")
print ((x/4)+y)
print ("Expressão B x * y ** 6")
print (x *(y**6))
print ("Expressão C (x % 4) , (((int) y * 10)//4")
print (x%4, (int(y*10)//4))
print ("Expressão D (x / 6 // x / 3) + 4")
print ((x / 6 // x / 3) + 4)